config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => 'registrations' }

  resources :songs
  resources :artists
  resources :tags, only: [:index, :show]
  resources :authentications, only: [:destroy]

  get 'my-songs', to: 'songs#my_songs'

  root 'songs#index'
end

app/models/artist.rb
class Artist < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name

  has_many :songs
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  access all: [:show, :index], user: {except: [:destroy, :edit]}, site_admin: :all

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.order('name ASC')
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @page_title = @artist.name
    @songs = @artist.songs.order('title ASC').page(params[:page]).per(20)
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= simple_form_for artist  do |form| %>

    <%= form.input :name, label: 'Name', error: 'Name should not be blank.' %>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing <%= @artist.name %></h1>

<%= render 'form', artist: @artist %>
<hr />
<%= link_to 'Show', @artist, class: 'btn btn-secondary' %>
<%= link_to 'Back', artists_path, class: 'btn btn-secondary' %>

app/views/artists/index.html.erb
<div class="row">
  <% if logged_in?(:site_admin) %>
    <div class="col">
      <%= link_to 'Add Artist', new_artist_path, class: 'btn btn-sm btn-primary' %>
    </div>
  <% end %>

</div>
<div id="artist-list" class="row">
  <div class="col">
    <ul class="list">
      <% @artists.each do |artist| %>

          <li><%= link_to artist.name, artist, class: 'bold' %></span>
            <% if logged_in?(:site_admin) %>
              <span><%= link_to 'Edit', edit_artist_path(artist), class: 'badge badge-success' %></span>
              <span><%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-danger' %></span>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>
<% if logged_in?(:site_admin) %>
<div class="meta">
  <span><%= link_to 'Edit Artist', edit_artist_path(@artist), class: 'badge badge-success' %> </span>
  <span><%= link_to 'Add Song', new_song_path, class: 'badge badge-primary' %></span>
  <span><%= link_to 'Back', artists_path, class: 'badge badge-secondary' %></span>
</div>
<% end %>
<hr />
<ul class="list">
  <% @songs.each do |song| %>
      <li><%= link_to song.title, song %></li>
  <% end %>
</ul>
<%= paginate @songs %>