config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => 'registrations' }

  resources :songs
  resources :artists
  resources :tags, only: [:index, :show]
  resources :authentications, only: [:destroy]

  get 'my-songs', to: 'songs#my_songs'

  root 'songs#index'
end

app/models/song.rb
class Song < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable

  validates_presence_of :title, :key, :body

  belongs_to :artist
  accepts_nested_attributes_for :artist

  def self.user_songs(current_user)
    where("user_id = #{current_user}")
  end

  def self.search(search)
    joins(:artist).where('LOWER(songs.title) LIKE ? OR LOWER(artists.name) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%")
  end

  def self.recent
    order("created_at DESC").limit(10)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :can_access, only: [:edit, :update]
  access all: [:show, :index], user: {except: [:destroy]}, site_admin: :all

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all.order('title ASC')
    if params[:search]
      @songs = Song.search(params[:search]).order('title ASC').page(params[:page]).per(20)
    else
      @songs = Song.all.order('title ASC').page(params[:page]).per(20)
    end
  end

  def my_songs
    @songs = Song.user_songs(current_user.id)
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @page_title = "#{@song.title} by #{@song.artist.name}"
  end

  # GET /songs/new
  def new
    @song = Song.new
    @user_id = current_user.id
  end

  # GET /songs/1/edit
  def edit
    @user_id = @song.user_id
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :key, :body, :artist_id, :user_id, :tag_list)
    end


    def can_access
      if current_user.id == @song.user_id or current_user.role == :site_admin
        return true
      else
        flash[:notice] = 'You can only edit or delete the Songs you added.'
        redirect_to songs_path
      end
    end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= simple_form_for song do |form| %>


    <div class="form-group">
      <%= form.hidden_field 'user_id', :value => @user_id, class: 'form-control' %>
    </div>


    <%= form.input :title, label: 'Song Title', error: 'Song Title is required' %>
  <div class="row">
    <div class="col-md-6">
      <%= form.input :artist_id, :collection => Artist.order(:name), label: 'Artist', error: 'Artist is required', include_blank: false %>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label 'Song Key' %> <br/>
        <%= form.collection_select :key, [['C', 'C'] ,['C#', 'C#'], ['Db', 'Db'], ['D', 'D'],['D#', 'D#'], ['Eb', 'Eb'], ['E', 'E'], ['F', 'F'], ['F#', 'F#'], ['Gb', 'Gb'], ['G', 'G'], ['G#', 'G#'], ['Ab', 'Ab'],['A', 'A'], ['A#', 'A#'], ['Bb', 'Bb'], ['B', 'B']], :first, :last  %>
      </div>
    </div>
  </div>



    <%= form.input :body, label: 'Body', error: 'Song Body is required.' %>
    <%=  form.input :tag_list %>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div class="tag-list"><%= link_to song.title, song_path(song) %></div>

app/views/songs/edit.html.erb
<h1>Editing <%= @song.title %></h1>

<%= render 'form', song: @song %>
<hr />
<%= link_to 'Show', @song, class: 'btn btn-secondary' %>
<%= link_to 'Back', songs_path, class: 'btn btn-secondary' %>

app/views/songs/index.html.erb
<div class="row">
  <% if logged_in?(:site_admin) %>
      <div class="col">
        <%= link_to 'Add Song', new_song_path, class: 'btn btn-sm btn-primary' %>
      </div>
  <% end %>

</div>
<div id="song-list" class="row">

  <div class="col">
    <% if @songs.any? %>
    <ul class="list">
    <% @songs.each do |song| %>

          <li><%= link_to song.title, song, class: 'bold' %> by <span class="artist"><%= link_to song.artist.name, song.artist %></span>
          <% if logged_in?(:site_admin) %>
            <span><%= link_to 'Edit', edit_song_path(song), class: 'badge badge-success' %></span>
            <span><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-danger' %></span>
          <% end %>
          </li>
    <% end %>
    </ul>
    <% else %>
        <div class="not-found">
          No songs found...
        </div>
    <% end %>
    <%= paginate @songs %>
  </div>
</div>

app/views/songs/my_songs.html.erb
<div class="row">
  <% if logged_in?(:site_admin) %>
      <div class="col">
        <%= link_to 'Add Song', new_song_path, class: 'btn btn-sm btn-primary' %>
      </div>
  <% end %>

</div>
<div id="song-list" class="row">
  <div class="col">
    <ul class="list">

      <% @songs.each do |song| %>

          <li><%= link_to song.title, song, class: 'bold' %> by <span class="artist"><%= link_to song.artist.name, song.artist %></span>

                <span><%= link_to 'Edit', edit_song_path(song), class: 'badge badge-success' %></span>
                <span><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-danger' %></span>

          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<h1 class="title"><%= @song.title %> <span>by <%= link_to @song.artist.name, @song.artist %></span>
</h1>

<% if user_signed_in? and (logged_in?(:site_admin) or current_user.id == @song.user_id) %>
    <%= link_to 'Edit', edit_song_path(@song), class: 'badge badge-primary' %>
<% end %>
<%= link_to 'Back', songs_path, class: 'badge badge-secondary' %>

<div class="meta">
  <ul>
    <li>Key: <span class="badge badge-secondary"><%= @song.key %></span>
    <% if @song.tags.count > 0 %>
          Tags: <%= render @song.tags %>
    <% end %>
    </li>
  </ul>
</div>
<div class="song-body">
  <pre data-key="<%= @song.key %>">
<%= @song.body %>
</pre>
</div>